### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_Blinka_Displayio#34]
I got this error while running the electioncal guide code. It took about 5 minutes for it to appear, so it wasn't immediate. It's possibly a Pillow bug. I need to look into it more.
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/displayio/display.py", line 244, in _refresh_loop
    self.refresh()
  File "/home/pi/.local/lib/python3.7/site-packages/displayio/display.py", line 231, in refresh
    self._current_group._fill_area(buffer)  # pylint: disable=protected-access
  File "/home/pi/.local/lib/python3.7/site-packages/displayio/group.py", line 160, in _fill_area
    layer._fill_area(buffer)  # pylint: disable=protected-access
  File "/home/pi/.local/lib/python3.7/site-packages/displayio/group.py", line 160, in _fill_area
    layer._fill_area(buffer)  # pylint: disable=protected-access
  File "/home/pi/.local/lib/python3.7/site-packages/displayio/group.py", line 160, in _fill_area
    layer._fill_area(buffer)  # pylint: disable=protected-access
  [Previous line repeated 1 more time]
  File "/home/pi/.local/lib/python3.7/site-packages/displayio/tilegrid.py", line 289, in _fill_area
    image, (round(x), round(y)), source=(round(source_x), round(source_y))
  File "/home/pi/.local/lib/python3.7/site-packages/PIL/Image.py", line 1541, in alpha_composite
    background = self.crop(box)
  File "/home/pi/.local/lib/python3.7/site-packages/PIL/Image.py", line 1134, in crop
    return self._new(self._crop(self.im, box))
  File "/home/pi/.local/lib/python3.7/site-packages/PIL/Image.py", line 1154, in _crop
    return im.crop((x0, y0, x1, y1))
OverflowError: Python int too large to convert to C long
```

**Comment by makermelissa** [comment]
The issue is that text is positioned so far out of bounds that the error occurs. The trick to fix this will be to not even attempt to add it if it's off the screen anyways.
