### ISSUE TITLE
ST7735R not working with PICO_U2IF (Raspberry PICO board)

### ISSUE THREAD

**Issue by cs0ckn** [adafruit/Adafruit_Blinka_Displayio#56]
When using the ST7735R display on the Mini TFT featherwing with PICO_U2IF on a Raspberry PICO I get error:-

Exception in thread Thread-1:
Traceback (most recent call last):
  File "I:\Python\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "I:\Python\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "I:\Python\lib\site-packages\displayio\display.py", line 248, in _refresh_loop
    self.refresh()
  File "I:\Python\lib\site-packages\displayio\display.py", line 244, in refresh
    self._refresh_display_area(area)
  File "I:\Python\lib\site-packages\displayio\display.py", line 288, in _refresh_display_area
    self._write(self._write_ram_command, pixels)
  File "I:\Python\lib\site-packages\displayio\display.py", line 204, in _write
    self._bus.send(False, data)
  File "I:\Python\lib\site-packages\displayio\fourwire.py", line 116, in send
    self._spi.write(data)
  File "I:\Python\lib\site-packages\busio.py", line 341, in write
    return self._spi.write(buf, start, end)
  File "I:\Python\lib\site-packages\adafruit_blinka\microcontroller\pico_u2if\spi.py", line 49, in write
    pico_u2if.spi_write(buf, start=start, end=end)
  File "I:\Python\lib\site-packages\adafruit_blinka\microcontroller\pico_u2if\pico_u2if.py", line 325, in spi_write
    bytes([write_cmd, chunk]) + buffer[start : (start + chunk)], True
TypeError: can't concat list to bytes

Seems to be similar to adafruit/Adafruit_Blinka#454 and changing displayio.display.py as intimated by @caternuson reply for that issue appears to fix it

 ```
pixels = list(
            numpy.dstack(((color >> 8) & 0xFF, color & 0xFF)).flatten().tolist()
        )
```
to
```
pixels = bytes(
           numpy.dstack(((color >> 8) & 0xFF, color & 0xFF)).flatten().tolist()
       )
```

**Comment by makermelissa** [comment]
Fixed via #57
